### ISSUE TITLE
examples 5,6, 8 compilation issue

### ISSUE THREAD

**Issue by Adrian-Diaz** [MASTmultiphysics/mast-multiphysics#110]
Greetings,

It seems that if I set -DENABLE_NLOPT=ON (one of the CMAKE List variables to enable compiling examples 5, 6, and 8) the compiler complains it can't find the interfaces for the SNOPT and GCMMA libraries when compiling the cpp files for these examples. It looks like the include files for those interfaces are only provided if -DENABLE_SNOPT=ON and -DENABLE_GCMMA=ON (In which case both libraries must be provided for the CMake configure). I'm not sure if there's a workaround I'm missing to make the examples work, thanks for any help rendered in advance.

**Comment by manavbhatia** [comment]
Greetings! 
These examples are currently setup for GCMMA or SNOPT interfaces. If you want to use this with NLOPT (for which we had added an interface, but never really used it for anything), then you will need to modify the source code for the examples and add a small section to instantiate the NLOPT optimization routine, for example [here](https://github.com/MASTmultiphysics/mast-multiphysics/blob/7860f77666031b1132448f10e4f8f632c6cb2676/examples/structural/example_5/example_5.cpp#L1824). 

Please note that this is the old MAST code, and most of our topology optimization work is happening on the new code base for [MAST v3](https://github.com/MASTmultiphysics/MAST3). Unless you have a compelling reason to work with old MAST, I would recommend moving to v3. The topology optimization approach in that is currently based on SIMP parameterization (old MAST had immersed boundary using cut-cells).

**Comment by Adrian-Diaz** [comment]
Greetings Dr. Bhatia,
Thanks for the prompt response and for directing me to version 3. I'll be sure to try with that version. Closing the issue :)
