### ISSUE TITLE
PointLoadSetType in PhysicsDiscipline

### ISSUE THREAD

**Issue by manavbhatia** [MASTmultiphysics/mast-multiphysics#19]
@JohnDN90 are you using the PointLoadSetType for any of your work? I am looking to add a more general point load data structure and can keep or remove this based on current utility.

**Comment by JohnDN90** [comment]
No, I'm not currently using it in any of my work.

**Comment by manavbhatia** [comment]
oh.. that was supposed to go to @jdeaton . 
Thanks anyways!

**Comment by jdeaton** [comment]
I'm using point loads, but not using that particular data structure to do it. I've been basically just directly adding values to R in specified degrees-of-freedom in a PostAssemblyOperation. I'd say remove it and let's implement something more general.

**Comment by manavbhatia** [comment]
Added point load condition to PhysicsDiscipline. This operates in the same way the other boundary conditions are applied. See the usage here in updated [Example 2](https://github.com/MASTmultiphysics/mast-multiphysics/blob/387852bba244a1c37e5e015d7a244eaa4450eb32/examples/structural/example_2/example_2.cpp#L245)
