### ISSUE TITLE
Structural example 4 reports zero stresses

### ISSUE THREAD

**Issue by wil-england** [MASTmultiphysics/mast-multiphysics#25]
I am trying to use tied constraints and sensitivities for a design optimization problem we are facing. I am running structural_example_4 as an example for how to accomplish this. However, when I run this example, the resulting mesh reports zero stresses across the entire domain.

I am running the following:
`./structural_example_4 -ksp_type preonly -pc_type lu`

The fields `structural_u` and `structural_t` are populated. My first guess is that displacement is being reported as zero and the resulting stress is thusly zero.

Any ideas on how to remedy this issue? Am I running this example correctly?

**Comment by manavbhatia** [comment]
This is a bit odd. I see that the intended changes recently pushed into the tie-constraint PR #24 never made it into the code. I must have really goofed up in setting up the PR. 

Since the changes in the commit did not make it into the PR, you are still getting the same results. 

I will get back to you on this shortly.

**Comment by manavbhatia** [comment]
I have located the changes that did not make it to the previous PR #24. I have submitted another PR #26, which should fix this. I will merge it once it passes the test. Hopefully this will address some of your needs. 

Note that I did not implement sensitivity analysis in this. I will add that shortly, but the analysis should give you plenty to move forward with.

**Comment by manavbhatia** [comment]
The PR #26 has been merged, which should provide boundary-to-subdomain tie-constraint capability. Please see [here](https://github.com/MASTmultiphysics/mast-multiphysics/blob/17ac90f0d53022c64825656dd09a38f0d2c23de6/examples/structural/example_4/example_4.cpp#L262).

**Comment by wil-england** [comment]
Thanks for this update.

I have again pulled and built and the example is now reporting stresses. We can now try to implement ties in our models.

**Comment by manavbhatia** [comment]
Sounds good. Let me know how this goes.
