### ISSUE TITLE
Build fails on files in tests/fluid/jacobians 

### ISSUE THREAD

**Issue by JohnDN90** [MASTmultiphysics/mast-multiphysics#28]
OS: Ubuntu 16.04
Compiler: GCC 5.4.0 (OpenMPI version 3.0.1)
Boost Version: 1.61

Compiling MAST fails at 99% on both the check_fluid_jacobian.cpp and check_fluid_eigenvector.cpp files.  In particular, it fails on [this line](https://github.com/MASTmultiphysics/mast-multiphysics/blob/17ac90f0d53022c64825656dd09a38f0d2c23de6/tests/fluid/jacobians/check_fluid_jacobian.cpp#L61) with the message 

> MAST_INSTALL/external_programs/MAST/tests/fluid/jacobians/check_fluid_eigenvectors.cpp:61:47: error: expected constructor, destructor, or type conversion before ‘;’ token
 BOOST_TEST_GLOBAL_FIXTURE( GlobalTestFixture );
                                               ^

If I comment out lines 60-64 in both files the build completes. However, as expected, this causes both tests (1/2 and 2/2) to fail when running make test.

Edit: Fixed quote block.

**Comment by manavbhatia** [comment]
I have seen this earlier, and this was the reason why I put the check for boost version 
```
#if BOOST_VERSION > 105800
```
Can you try changing this to 106100 to see if it works. Maybe the change in the fixture setup happened after version 1.61.

**Comment by JohnDN90** [comment]
It compiles successfully with that change, bu running "make test" results in

> Running tests...
Test project /home/john_mast/Programs/MAST_INSTALL/external_programs/MAST/opt
    Start 1: fluid_jacobian
1/2 Test #1: fluid_jacobian ...................***Failed    2.71 sec
    Start 2: fluid_eigen_vec
2/2 Test #2: fluid_eigen_vec ..................   Passed    0.24 sec
50% tests passed, 1 tests failed out of 2
Total Test time (real) =   3.02 sec
The following tests FAILED:
	  1 - fluid_jacobian (Failed)
Errors while running CTest
Makefile:105: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by manavbhatia** [comment]
This may have to do with the finite-difference comparison of Jacobians that don't always match and can lead to issues. I am working to do a major overhaul the test suite with automatic differentiation. 
I would ignore this error at this point.

**Comment by JohnDN90** [comment]
That makes sense.  Thanks for the help on that.
