### ISSUE TITLE
MAST::NO_BENDING calling TimoshenkoBendingOperator in 1D analysis

### ISSUE THREAD

**Issue by JohnDN90** [MASTmultiphysics/mast-multiphysics#41]
I actually just discovered the bending_operator stuff last week. But when I tried using it and set NO_BENDING in a 1D extension example problem, I get an error indicating "property not found for : kappa".  Looking at the stack trace, it looks like the TimoshenkoBendingOperator is calling the calculate_transverse_shear_residual.  It seems odd that NO_BENDING is resulting in the TimoshenkoBendingOperator being called, but I haven't look through the code to see how you implemented it yet.

_Originally posted by @JohnDN90 in https://github.com/MASTmultiphysics/mast-multiphysics/issues/40#issuecomment-541158428_

**Comment by JohnDN90** [comment]
After modifying StructuralElement1D to print the MAST::BendingOperatorType, it shows that the operator type is set to 1 (TIMOSHENKO) regardless of what value I set using section.set_bending_model().  I suspect the issue is in element_property_card_1D.cpp, but still looking to identify the issue.

**Comment by manavbhatia** [comment]
The issue is likely [here](https://github.com/MASTmultiphysics/mast-multiphysics/blob/49128573760e3dd2b9485fc8dfb0c0221c395b5a/src/property_cards/element_property_card_1D.cpp#L29) since it guesses the operator type based on the element type. If you add NO_BENDING to this logic then it should work fine. 

Likewise for 2D elements [here](https://github.com/MASTmultiphysics/mast-multiphysics/blob/49128573760e3dd2b9485fc8dfb0c0221c395b5a/src/property_cards/element_property_card_2D.cpp#L30).

**Comment by JohnDN90** [comment]
Issue was [here](https://github.com/MASTmultiphysics/mast-multiphysics/blob/master/src/property_cards/element_property_card_1D.cpp#L37).  Logic was set so that if it an EDGE2 element did not have MAST::DEFAULT_BENDING set, it would only return Timoshenko bending.  I changed it to return _bending_model instead.

A new issues however, is that when NO_BENDING is set, the extension (which an element aligned along the y-axis) doesn't solve but returns a zero solution without throwing an error.  Now looking into this.

**Comment by JohnDN90** [comment]
Hmm, the issue with the zero solution when using NO_BENDING is interesting.

The only way I can get the true solution is using  a direct solve with LU decomposition performed by mkl_pardiso.  The default PETSc options, and even a direct solve with LU decomp using other packages doesn't work "superlu", "umfpack", "mumps".

I'm not sure what's causing the issue, but seems like its something mkl_pardiso is smart enough to detect and correct.

**Comment by manavbhatia** [comment]
NO_BENDING will cause zero entries for stiffness matrix related to bending dofs. So, with this option, the structural_elem_1D should add small epsilon terms to the diagonal of the element stiffness matrix. These should be epsilon times the largest diagonal entry in the matrix. We are already doing this for the theta_z dofs of the 2D elements, which do not get any contribution from either the membrane or bending terms.

**Comment by JohnDN90** [comment]
Great, thank you.

I added some code to MAST::StructuralElement1D::internal_residual to add a small value to the diagonal and it seems to be working now.

**Comment by JohnDN90** [comment]
This should be fixed in the upcoming catch2 unit tests capability pull request.  Once we confirm its been merged into master we can then close this issue.
