### ISSUE TITLE
Possibly move shear correction factor to section property card

### ISSUE THREAD

**Issue by JohnDN90** [MASTmultiphysics/mast-multiphysics#42]
Josh and I have discussed this a few times.  It seems like  the shear correction factor (kappa) might be better suited as a section property as opposed to a material property.

According to [this,](https://en.wikipedia.org/wiki/Timoshenko_beam_theory#Shear_coefficient) it looks like kappa is a function of both the geometry and Poisson's ratio.  However, most FEA programs treat it as a section property.  For MAST to be a little more intuitive for both users and developers (and to help reduce the learning curve for potential future users), it may be worthwhile to move kappa from a material property to a section property card.

We'd like to get your thoughts on this.

**Comment by manavbhatia** [comment]
I have never used kappa other than a 5/6 ratio and my knowledge of how to evaluate it for specific sections and materials is limited. 

How often do you anticipate using a different value for kappa? Also, if you move this to section property card, do you anticipate computing values for kappa using any of the section property card parameters? 

If not, then this would mostly be a nomenclature issue to fit a broader community understanding? 

I don’t have any strong feelings either ways, but we will need to modify all our examples to fit this modification. 

This will also need modifications in the section property card routines since it expects the material card to provide these values.

**Comment by JohnDN90** [comment]
It's primarily a nomenclature issue to fit a broader understanding.  On our side, most potential users have a Nastran background, so making MAST's setup more inline with Nastran should help reduce the learning curve for new users.

From a Nastran interface perspective, it makes reading in an input file a little more complicated because if a Nastran model has multiple sections due to differing kappas, then that would have to be mapped to multiple material cards in the MAST model.

To my knowledge, at the moment we don't have any use cases with differing values of kappa.

**Comment by manavbhatia** [comment]
Thanks for the clarification. 
I think it makes sense to move kappa to section card.

**Comment by JohnDN90** [comment]
I've moved `kappa` from the material card to the section card.  In additional, for 1D elements I've allowed `kappa_zz` and `kappa_yy` to be specified separately since it seems that for most cross sections they are not equal.

This changed should be implemented in the upcoming catch2 unit tests capability pull request. Once we confirm its been merged into master we can then close this issue.

**Comment by JohnDN90** [comment]
> How often do you anticipate using a different value for kappa? 

Since I linked the pull request to this issue, I feel I should better address some of these questions.  At the moment, I don't expect kappa to vary much for 2D sections.  However, for 1D sections it seems that kappa can vary a lot based on the cross sectional shape, and it can be different in the y- and z-directions.  

> Also, if you move this to section property card, do you anticipate computing values for kappa using any of the section property card parameters?

With the current pull request that is linked to this issue, kappa is still specified by the user for 2D sections.  However, for 1D sections, kappa is calculated using section property card parameters.
