### ISSUE TITLE
CI document deployment failing

### ISSUE THREAD

**Issue by manavbhatia** [MASTmultiphysics/mast-multiphysics#55]
@jdeaton it appears that CI is building the docs, but failing to deploy it: 
[https://travis-ci.com/MASTmultiphysics/mast-multiphysics/jobs/275615995](https://travis-ci.com/MASTmultiphysics/mast-multiphysics/jobs/275615995)

**Comment by jdeaton** [comment]
I noticed that. I'll sort it out tomorrow.

**Comment by jdeaton** [comment]
Merge request #56 closes this issue. Documentation is successfully deployed. 

I've also noticed that it takes a few minutes for updates to the GitHub host repository to disseminate throughout their content delivery network (CDN). This means after a successful documentation deployment from Travis-CI back to the host repo there could be a several minute delay where an older cached version of the website still shows. This is normal and will resolve itself after some time. The only way to make updates show faster is to move to an actual dedicated web host.
