### ISSUE TITLE
Organization of examples/tutorials.

### ISSUE THREAD

**Issue by jdeaton** [MASTmultiphysics/mast-multiphysics#7]
This issue is for discussion of how to organize the example programs for the MAST library. We have previously decided that each example program meant for users to use to learn with should be stand-alone (something like the example_driver or more build-up programs might be good for tests). We also decided that we like the highly commented tutorial examples in the deal-ii library.

Since there are already a lot of examples I propose that we get as many of them as we can organized as independent programs and broken out of the example_driver. In doing this, we might also want to consider how to use them appropriately with an automated testing framework.

In parallel to this, we should start a series of "tutorial" examples that are heavily commented like deal-ii. These should start with a simple example, and progressively add more complexity/capability to it with later steps. I think we can use either CMake or doxygen to create the HTML pages like is done in deal-ii for the tutorial portions.

To me this implies a directory structure for the time being as something like:
- `examples/tutorial/step-1`
- `examples/tutorial/step-2`
- `examples/tutorial/step-n`
- `examples/fluid/*`
- `examples/fsi/*`
- `examples/structural/*`
- `examples/thermal/*`

**Comment by manavbhatia** [comment]
Agreed. I will pull the Cmake update branch into master on MAST and then you can use that for your spack installer. Then we can continue populating that with the tutorials/etc.
